name: "Schengen Slot Watcher (Multi-Country)"

permissions:
  contents: write

on:
  schedule:
    - cron: "*/45 * * * *"   # every 45 minutes
  workflow_dispatch:

jobs:
  watch_slots:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        city: ["dubai", "abu-dhabi"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      # … steps 2–7 unchanged …

      # 8) Only commit and push last_state_<city>.json if it exists & changed
      - name: Commit updated last_state file if needed
        run: |
          if [ -f last_state_${{ matrix.city }}.json ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            # Fetch the latest remote commit(s), then rebase our new JSON
            git fetch origin main
            git rebase origin/main
            git add last_state_${{ matrix.city }}.json
            git diff --cached --quiet || git commit -m "Update last_state_${{ matrix.city }}.json"
            git push origin HEAD:main
          else
            echo "No last_state_${{ matrix.city }}.json to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
