name: "Schengen Slot Watcher"

on:
  schedule:
    - cron: "*/5 * * * *"      # run every 5 minutes
  workflow_dispatch:

jobs:
  watch_slots:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true   # needed for the final “push” step

      # 2) Set up Python and install pip dependencies
      - name: Set up Python & Install dependencies
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # 3) Set up Node.js (needed for Playwright)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # 4) Install Playwright and all system dependencies
      - name: Install Playwright + Browsers (with deps)
        run: |
          npm install playwright
          # The --with-deps flag installs required apt packages too
          npx playwright install --with-deps

      # 5) Render the live page (with JavaScript) into rendered.html
      - name: Render Schengen appointments HTML
        run: |
          node << 'EOF'
          const { chromium } = require('playwright');
          (async () => {
            const browser = await chromium.launch({ headless: true });
            const page = await browser.newPage();
            // Navigate to the live site (City slug + Visa type)
            await page.goto(
              `https://schengenappointments.com/in/${process.env.CITY_SLUG}/${process.env.VISA_TYPE}`,
              { timeout: 60000 }
            );
            // Wait until at least one <tr> appears inside the <tbody>
            await page.waitForSelector('tbody tr', { timeout: 60000 });
            const html = await page.content();
            const fs = require('fs');
            fs.writeFileSync('rendered.html', html, 'utf-8');
            await browser.close();
          })();
          EOF
        env:
          CITY_SLUG: "dubai"
          VISA_TYPE: "tourism"

      # 6) (Optional) Show first lines of rendered.html for debugging
      - name: Debug  Show rendered HTML snippet
        if: always()
        run: |
          echo "----- BEGIN rendered.html (lines 1–40) -----"
          head -n 40 rendered.html
          echo "------ END rendered.html ------"

      # 7) Run the Python checker (which now parses rendered.html)
      - name: Run Schengen slot checker
        env:
          CITY_SLUG:      "dubai"
          VISA_TYPE:      "tourism"
          TARGET_COUNTRY: "Luxembourg"
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID:        ${{ secrets.CHAT_ID }}
          STATE_FILE:     "last_state.json"
        run: |
          python check_schengen.py

      # 8) If last_state.json changed, commit & push it back to main
      - name: Commit updated state.json if needed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add last_state.json
          git diff --cached --quiet || git commit -m "Update last_state.json"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
