# .github/workflows/check_schengen.yml

name: "Schengen Slot Watcher"

on:
  schedule:
    - cron: "*/5 * * * *"      # every 5 minutes
  workflow_dispatch:           # manual trigger

jobs:
  watch_slots:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repo (so we have check_schengen.py)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true   # so we can push last_state.json back

      # 2) Install Python & pip packages
      - name: Set up Python & install deps
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # 3) Install Node.js (needed for Playwright)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # 4) Use the official Playwright Action to install browsers automatically
      - name: Install Playwright browsers
        uses: microsoft/playwright-github-action@v1
        with:
          # By default, this will install Chromium, WebKit, and Firefox for Playwright
          playwright-version: "1.37.1"  # you can pin to the latest or a specific version

      # 5) Render the live page (with JavaScript) into rendered.html
      - name: Render Schengen appointments HTML
        run: |
          node << 'EOF'
          const { chromium } = require('playwright');
          (async () => {
            const browser = await chromium.launch({ headless: true });
            const page = await browser.newPage();
            // Go to the live site:
            await page.goto(
              `https://schengenappointments.com/in/${process.env.CITY_SLUG}/${process.env.VISA_TYPE}`,
              { timeout: 60000 }
            );
            // Wait until at least one table row appears:
            await page.waitForSelector('tbody tr', { timeout: 60000 });
            const html = await page.content();
            const fs = require('fs');
            fs.writeFileSync('rendered.html', html, 'utf-8');
            await browser.close();
          })();
          EOF
        env:
          CITY_SLUG: "dubai"
          VISA_TYPE: "tourism"

      # 6) (Optional) Peek at rendered.html to verify it actually contains table rows
      - name: Debug  Show rendered HTML snippet
        if: always()
        run: |
          echo "----- FIRST 40 LINES OF rendered.html -----"
          head -n 40 rendered.html
          echo "------ END SNIPPET ------"

      # 7) Run the Python script, which now reads rendered.html instead of doing requests.get()
      - name: Run Schengen slot checker
        env:
          CITY_SLUG:      "dubai"
          VISA_TYPE:      "tourism"
          TARGET_COUNTRY: "Luxembourg"
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID:        ${{ secrets.CHAT_ID }}
          STATE_FILE:     "last_state.json"
        run: |
          python check_schengen.py

      # 8) If last_state.json changed, commit & push it back to main
      - name: Commit updated state.json if needed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add last_state.json
          git diff --cached --quiet || git commit -m "Update last_state.json"
          git push origin HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
