name: "Schengen Slot Watcher"

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  watch_slots:
    runs-on: ubuntu-latest

    steps:
      # ─── 0. (NEW) Print the entire workspace directory structure ────────────
      - name: Debug: List workspace files
        run: |
          echo "------ PWD ------"
          pwd
          echo "------ ls -R . ------"
          ls -R .

      # ─── 1. Checkout repository ─────────────────────────────────────────────
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      # ─── 2. Set up Python ───────────────────────────────────────────────────
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # ─── 3. Install dependencies ───────────────────────────────────────────
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # ─── 4. (NEW) Show the first 20 lines of check_schengen.py ────────────
      - name: Show check_schengen.py contents
        run: |
          echo "------ BEGIN check_schengen.py (lines 1–20) ------"
          sed -n '1,20p' check_schengen.py
          echo "------- END check_sc_
