name: "Schengen Slot Watcher"

on:
  schedule:
    - cron: "*/25 * * * *"   # every 45 minutes
  workflow_dispatch:        # allow manual runs

jobs:
  watch_slots:
    runs-on: ubuntu-latest

    # ─── Use a matrix to run the same steps for both 'dubai' and 'abu-dhabi' ───
    strategy:
      matrix:
        city: ["dubai", "abu-dhabi"]

    steps:
      # 1) Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true   # needed for the final git push

      # 2) Set up Python and install pip dependencies
      - name: Set up Python & Install Python deps
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      # 3) Set up Node.js (for Playwright)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # 4) Install Playwright + all system dependencies
      - name: Install Playwright + Browsers (with deps)
        run: |
          npm install playwright
          npx playwright install --with-deps

      # 5) Render the live page for the current matrix city into rendered_<city>.html
      - name: Render Schengen HTML for ${{ matrix.city }}
        run: |
          node << 'EOF'
          const { chromium } = require('playwright');
          (async () => {
            const browser = await chromium.launch({ headless: true });
            const page = await browser.newPage();
            // build the exact URL from the city slug and VISA_TYPE
            const url = `https://schengenappointments.com/in/${process.env.CITY_SLUG}/${process.env.VISA_TYPE}`;
            await page.goto(url, { timeout: 60000 });
            await page.waitForSelector('tbody tr', { timeout: 60000 });
            const html = await page.content();
            const fs = require('fs');
            fs.writeFileSync(`rendered_${process.env.CITY_SLUG}.html`, html, 'utf-8');
            await browser.close();
          })();
          EOF
        env:
          # override CITY_SLUG with the current matrix value:
          CITY_SLUG: ${{ matrix.city }}
          VISA_TYPE: "tourism"

      # 6) (Optional) Debug: show the first 40 lines of rendered_<city>.html
      - name: Debug: Show rendered_${{ matrix.city }}.html snippet
        if: always()
        run: |
          echo "----- BEGIN rendered_${{ matrix.city }}.html (lines 1–40) -----"
          head -n 40 rendered_${{ matrix.city }}.html
          echo "------ END rendered_${{ matrix.city }}.html ------"

      # 7) Run our Python checker, pointing it at rendered_<city>.html and a state file unique to this city
      - name: Run Schengen slot checker for ${{ matrix.city }}
        env:
          CITY_SLUG:      ${{ matrix.city }}
          VISA_TYPE:      "tourism"
          TARGET_COUNTRY: "Italy"
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID:        ${{ secrets.CHAT_ID }}
          # Each city gets its own state file:
          STATE_FILE:     "last_state_${{ matrix.city }}.json"
        run: |
          python check_schengen.py

      # 8) Only commit and push last_state_<city>.json if it exists & changed
      - name: Commit updated last_state file if needed
        run: |
          if [ -f last_state_${{ matrix.city }}.json ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users
